#!/bin/bash
if [ $# -ne 2 ]
then
	echo "Usage: train TAGGEDWORD NUMBER"
	exit 1
fi
SPRIOC="$1"
UIMHIR="$2"
CANDS=`mktemp`
egrep -h "${SPRIOC}" /home/kps/gaeilge/ga2gd/beostem/*.txt | randomize | sed -n "1,${UIMHIR}p" > $CANDS
perl trainer.pl "$SPRIOC" "$CANDS"
rm -f $CANDS
